/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class CommonConstants {
  /**
   * Zero.
   */
  static readonly ZERO: number = 0;

  /**
   * One.
   */
  static readonly ONE: number = 1;

  /**
   * Negative one.
   */
  static readonly NEGATIVE_ONE: number = -1;

  /**
   * Three.
   */
  static readonly THREE: number = 3;

  /**
   * Ten.
   */
  static readonly TEN: number = 10;

  /**
   * Twenty-one.
   */
  static readonly TWENTY_ONE: number = 21;

  /**
   * Canvas width.
   */
  static readonly CANVAS_WIDTH: number = 750;

  /**
   * One hundred.
   */
  static readonly ONE_HUNDRED: number = 100;

  /**
   * String empty.
   */
  static readonly COLOR_STRING: string = '';

  /**
   * Percent sign.
   */
  static readonly SIGN: string = '%';

  /**
   * Basic color.
   */
  static readonly BLACK: string = 'black';

  /**
   * One hundred percent.
   */
  static readonly ONE_HUNDRED_PERCENT: string = '100%';

  /**
   * Arr color.
   */
  static readonly COLOR_ARR: string[] = ['#E90808', '#63B959', '#0A59F7', '#E56224', '#F6C800', '#5445EF', '#A946F1',
    '#000000']

  /**
   * White.
   */
  static readonly WHITE: string = '#ffffff';

  /**
   * Detents.
   */
  static readonly DETENTS: [Length, Length] = [550, 600];
}